# Generated by Django 4.2.1 on 2023-05-22 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "availability_change_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "content_change_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compiler_app.catalog",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "availability_change_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "content_change_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("actual_file", models.FileField(upload_to="files/")),
                (
                    "holder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compiler_app.catalog",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SectionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200, unique=True)),
                ("css_class", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="FileSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("section_start", models.IntegerField()),
                ("section_end", models.IntegerField()),
                ("status_data", models.TextField(blank=True)),
                ("section_data", models.TextField()),
                (
                    "section_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compiler_app.file",
                    ),
                ),
                (
                    "section_status",
                    models.ForeignKey(
                        default=4,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compiler_app.sectionstatus",
                    ),
                ),
                (
                    "section_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compiler_app.sectiontype",
                    ),
                ),
            ],
        ),
    ]
