# Generated by Django 4.2.1 on 2023-05-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compiler_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectiontype",
            name="name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
