# Generated by Django 4.2.1 on 2023-05-24 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compiler_app", "0002_sectiontype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="actual_file",
            field=models.FileField(
                upload_to="files/",
                validators=[django.core.validators.FileExtensionValidator(["c"])],
            ),
        ),
    ]
