# Generated by Django 4.2.1 on 2023-05-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compiler_app", "0004_alter_filesection_section_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionstatus",
            name="status",
            field=models.CharField(max_length=30),
        ),
    ]
